[package]
name = "moka_cache"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "moka_cache"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
moka = { version = "0.7.1", features = ["future"] }
once_cell = "1.9.0"
rustler = "0.23.0"
